version: "3"

services:
  mysql:
    image: mysql
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass 
    ports:
      - "3306:3306"
    expose:
      - "3306"
  web:
    image: jaimemorillo/contafin:latest
    container_name: web_server
    depends_on: 
      - mysql
    container_name: web_server
    ports:
      - "8080:8080"
