version: "3.6"

services:
  mysql:
    image: mysql
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: pass 
    ports:
      - "3307:3306"
    expose:
      - "3306"
  web:
    image: jaimemorillo/contafin
    depends_on: 
      - mysql
    container_name: web_server
    ports:
      - "8080:8080"
